openapi: 3.0.0
info:
  title: RAG Chatbot API
  version: 1.0.0
  description: API for the Retrieval Augmented Generation (RAG) Chatbot.
servers:
  - url: http://localhost:8000
    description: Local development server
tags:
  - name: Chat
    description: Chatbot interaction endpoints
  - name: Documents
    description: Document management endpoints
paths:
  /chat:
    post:
      summary: Send a message to the chatbot
      description: Sends a user message to the RAG chatbot and receives a response.
      tags:
        - Chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: The user's query or message.
                  example: "What is a Retrieval Augmented Generation chatbot?"
                session_id:
                  type: string
                  description: Optional session ID for conversational context.
                  nullable: true
                  example: "user-session-123"
      responses:
        '200':
          description: Successful response from the chatbot.
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The chatbot's generated answer.
                    example: "A Retrieval Augmented Generation (RAG) chatbot combines information retrieval with text generation to provide more accurate and contextually relevant responses."
                  source_documents:
                    type: array
                    description: A list of documents used to generate the answer.
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The ID of the source document.
                        content_snippet:
                          type: string
                          description: A relevant snippet from the source document.
                        metadata:
                          type: object
                          description: Additional metadata from the source document.
                          additionalProperties: true
        '400':
          description: Invalid input provided.
        '500':
          description: Internal server error.

  /documents:
    post:
      summary: Upload a document for indexing
      description: Uploads a new document to be processed, embedded, and stored in the vector database.
      tags:
        - Documents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: The full textual content of the document.
                  example: "Retrieval Augmented Generation (RAG) is an architectural pattern that enhances the capabilities of large language models (LLMs) by integrating them with an information retrieval system."
                metadata:
                  type: object
                  description: Optional metadata for the document (e.g., source, title).
                  additionalProperties: true
      responses:
        '200':
          description: Document successfully uploaded and indexed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID of the newly created document.
                    example: "doc-123-abc"
                  status:
                    type: string
                    example: "indexed"
        '400':
          description: Invalid document format or content.
        '500':
          description: Internal server error during document processing.
    get:
      summary: Retrieve indexed documents
      description: Retrieves a list of all indexed documents, optionally filtered.
      tags:
        - Documents
      parameters:
        - name: query
          in: query
          description: Optional search query to filter documents.
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of documents to return.
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: List of documents.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Unique ID of the document.
                    content:
                      type: string
                      description: Full text content of the document.
                    metadata:
                      type: object
                      description: Metadata associated with the document.
                      additionalProperties: true
        '500':
          description: Internal server error.
